@baseUrl = http://localhost:3000/api
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "username": "richard",
    "password": "Stallman"
}

### 
# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "username": "richard",
    "password": "Stallman"
}

###
@authToken = {{login.response.body.$.access_token}}

### 
# @name refresh
GET {{baseUrl}}/auth/refresh

###
@authToken = {{login.response.body.$.access_token}}

POST {{baseUrl}}/notes/createNote
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Nota de Richard",
    "content": "Esto es una nota de Richard"
}

### Try create note without bearer
POST {{baseUrl}}/notes/createNote
Content-Type: application/json

{
    "title": "Nota de Richard 2",
    "content": "Esto es una nota de Richard 2"
}

### Get user notes
GET {{baseUrl}}/notes
Authorization: Bearer {{authToken}}
### Get Note info
GET {{baseUrl}}/notes/85581cbc-624f-4340-827c-74310bd03593
Authorization: Bearer {{authToken}}
### Update note
PUT {{baseUrl}}/notes/updateNote/85581cbc-624f-4340-827c-74310bd03593
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Nota de Richard",
    "content": "Esto es una nota modificada de Richard"
}
### Delete note
DELETE {{baseUrl}}/notes/deleteNote/85581cbc-624f-4340-827c-74310bd03593
Authorization: Bearer {{authToken}}
